version: "3"
services:
  pg:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: postgresql_sample
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
volumes:
  postgresql-data: